name: Lint Python Code

on:
  pull_request:
    branches: main

  push:
    branches: main
  workflow_dispatch: # run the workflow manually

  

jobs:
  lint: # The name of the job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Check Python
        run: python --version

      - name: Check pip
        run: pip --version

      - name: Lint Python Code
        uses: Omarkhattab146/devOps-tester/.github/workflows/test.yml@main

